version: "3"
volumes:
  db:
services:
  db:
    image: mysql
    ports:
      - "${CONTRACK_MYSQL_PORT:-3306}:3306"
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/mysql
      - ./sql:/etc/mysql/conf.d
  contrack:
    build: .
    ports:
      - "${CONTRACK_WEB_PORT:-8080}:80"
    volumes:
      - ./contrack:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - /var/www/html/uploads